name: 执行Python代码
on:
  workflow_dispatch: 

jobs: 
    build: 
        runs-on: ubuntu-latest 
        steps: 
          - name: Checkout repository 
            uses: actions/checkout@v2

          - name: Set up Python 
            uses: actions/setup-python@v2 
            with: 
                python-version: '3.12'

          - name: Install dependencies 
            run: |
                sudo pip install ping3

          - name: Run script 
            run: |
                sudo python python/ping.py
                python3 python/demo_print.py
